/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CommonUploadSuccessData { 
    /**
     * 檔案名稱(firebase比對用)
     */
    fileName?: string;
    /**
     * 檔案網址
     */
    fileUrl?: string;
    /**
     * 檔案大小
     */
    fileSize?: number;
}