/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardBoxOfficeChartSuccessDataPercentChartData } from './dashboardBoxOfficeChartSuccessDataPercentChartData';
import { DashboardBoxOfficeChartSuccessDataRankChartData } from './dashboardBoxOfficeChartSuccessDataRankChartData';

export interface DashboardBoxOfficeChartSuccessData { 
    /**
     * 票房佔比
     */
    percentChartData?: Array<DashboardBoxOfficeChartSuccessDataPercentChartData>;
    rankChartData?: DashboardBoxOfficeChartSuccessDataRankChartData;
}