/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 當日營收
 */
export interface DashboardMetricSuccessDataDailyIncome { 
    /**
     * 當日總收入
     */
    total?: number;
    /**
     * 漲幅百分比(相較昨日)
     */
    increasePercent?: number;
}