/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardBoxOfficeChartSuccessData } from './dashboardBoxOfficeChartSuccessData';

export interface DashboardBoxOfficeChartSuccess { 
    code?: number;
    message?: string;
    data?: DashboardBoxOfficeChartSuccessData;
}