/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LoginResData { 
    /**
     * 員工編號
     */
    staffId?: string;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 令牌
     */
    token?: string;
}