/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserProfileResData { 
    /**
     * 員工編號
     */
    staffId?: string;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 角色
     */
    role?: string;
    /**
     * 在職狀態(0:離職,1:在職)
     */
    status?: number;
    /**
     * 大頭貼圖片網址
     */
    stickerUrl?: string;
    /**
     * 大頭貼檔案名稱(firebase比對用)
     */
    stickerFileName?: string;
}