/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CommonOptionSuccessDataItem { 
    /**
     * 選項文字
     */
    name?: string;
    /**
     * 選項值
     */
    value?: number;
}