/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 票房排行
 */
export interface DashboardBoxOfficeChartSuccessDataRankChartData { 
    /**
     * 電影名稱(Y軸)
     */
    name?: Array<string>;
    /**
     * 電影票房金額(X軸)
     */
    value?: Array<number>;
}