/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MovieDetailResReleaseDate } from './movieDetailResReleaseDate';

export interface MovieDetailRes { 
    /**
     * 電影編號
     */
    id?: string;
    /**
     * 電影中文名
     */
    title?: string;
    /**
     * 電影英文名
     */
    enTitle?: string;
    /**
     * 電影類型
     */
    genre?: Array<number>;
    /**
     * 片長
     */
    runtime?: number;
    /**
     * 支援設備
     */
    provideVersion?: Array<number>;
    /**
     * 分級制度
     */
    rate?: number;
    /**
     * 導演
     */
    director?: string;
    /**
     * 演員
     */
    cast?: Array<string>;
    /**
     * 電影簡介
     */
    description?: string;
    /**
     * 上映狀態
     */
    status?: number;
    releaseDate?: MovieDetailResReleaseDate;
    /**
     * 預告片連結
     */
    trailerLink?: string;
    /**
     * 發行商
     */
    distributor?: string;
    /**
     * 海報連結
     */
    posterUrl?: string;
}