/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PatchOrderReqInner { 
    /**
     * orderID
     */
    id: string;
    /**
     * 付款狀態(-1:付款失敗,0:未付款,1:已付款,2:部分退款,3:全部退款)
     */
    status: number;
    /**
     * 扣款金額
     */
    newAmount: number;
}