/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ScheduleItem { 
    /**
     * 場次ID
     */
    scheduleId: string;
    /**
     * 電影開始時間
     */
    time: string;
    /**
     * 幾廳
     */
    theater: string;
    /**
     * 電影種類(1:2D、2:3D、3:iMAX、4:4DX)
     */
    theaterType: number;
    /**
     * 總座位
     */
    totalCapacity: number;
    /**
     * 剩餘座位
     */
    remainSeats: number;
}