/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Row } from './row';

export interface SeatResData { 
    /**
     * 已售數量
     */
    sold: number;
    /**
     * 已鎖數量
     */
    lock?: number;
    /**
     * 未售數量
     */
    free: number;
    /**
     * 總Rows
     */
    maxRows: number;
    /**
     * 總Columns
     */
    maxColumns: number;
    /**
     * row項目
     */
    rowLabel: Array<string>;
    /**
     * col項目
     */
    colLabel: Array<string>;
    list: Array<Row>;
}