/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StaffOrderSearchSuccessDataTime } from './staffOrderSearchSuccessDataTime';

export interface StaffOrderSearchSuccessDataTicketList { 
    /**
     * 票券ID
     */
    ticketId?: string;
    time?: StaffOrderSearchSuccessDataTime;
    /**
     * 票種名稱
     */
    type?: string;
    /**
     * 票價
     */
    price?: number;
    /**
     * 座位號
     */
    seatName?: string;
}