/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
<<<<<<< HEAD
import { TimetableCreateReqTheaterId } from './timetableCreateReqTheaterId';
import { TimetableListResDataEndDate } from './timetableListResDataEndDate';
import { TimetableListResDataStartDate } from './timetableListResDataStartDate';
=======
>>>>>>> develop

export interface TimetableCreateReq { 
    /**
     * 電影ID
     */
    movieId: string;
<<<<<<< HEAD
    theaterId: TimetableCreateReqTheaterId;
    startDate: TimetableListResDataStartDate;
    endDate: TimetableListResDataEndDate;
=======
    /**
     * 廳院ID
     */
    theaterId: string;
    /**
     * 開始時間
     */
    startDate: string;
    /**
     * 結束時間
     */
    endDate: string;
>>>>>>> develop
}