/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
<<<<<<< HEAD
import { TimetableListResDataEndDate } from './timetableListResDataEndDate';
import { TimetableListResDataStartDate } from './timetableListResDataStartDate';
=======
>>>>>>> develop

export interface TimetableUpdateReq { 
    /**
     * id
     */
    id: string;
    /**
     * 電影ID
     */
    movieId: string;
    /**
     * 廳院ID
     */
    theaterId: string;
<<<<<<< HEAD
    startDate: TimetableListResDataStartDate;
    endDate: TimetableListResDataEndDate;
=======
    /**
     * 開始時間
     */
    startDate: number;
    /**
     * 結束時間
     */
    endDate: number;
>>>>>>> develop
}