/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TimetableListResDataInner { 
    /**
     * id
     */
    id?: string;
    /**
     * 電影資料
     */
    movieId?: any;
    /**
     * 廳院資訊
     */
    theaterId?: any;
    /**
     * 開始時間
     */
    startDate?: string;
    /**
     * 結束時間
     */
    endDate?: string;
    /**
     * 新增時間
     */
    createdAt?: Date;
    /**
     * 更新時間
     */
    updatedAt?: Date;
}