/**
 * CinePOS_BackEnd
 * CinePOS 後端API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserProfileResData } from './userProfileResData';

export interface UserProfileRes { 
    code?: number;
    message?: string;
    data?: UserProfileResData;
}